// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Travely.Data;

#nullable disable

namespace Travely.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LkpAmenityTblHotel", b =>
                {
                    b.Property<int>("AmenitiesAmenityId")
                        .HasColumnType("int");

                    b.Property<int>("HotelsHotelId")
                        .HasColumnType("int");

                    b.HasKey("AmenitiesAmenityId", "HotelsHotelId");

                    b.HasIndex("HotelsHotelId");

                    b.ToTable("LkpAmenityTblHotel");
                });

            modelBuilder.Entity("Travely.Models.LkpAmenity", b =>
                {
                    b.Property<int>("AmenityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("amenity_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AmenityId"));

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("AmenityId")
                        .HasName("PK__lkpAmeni__E908452D58205242");

                    b.HasIndex(new[] { "Name" }, "UQ__lkpAmeni__72E12F1B6FB36A1B")
                        .IsUnique()
                        .HasFilter("[name] IS NOT NULL");

                    b.ToTable("lkpAmenities", (string)null);
                });

            modelBuilder.Entity("Travely.Models.TblBooking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<byte>("Adults")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("adults");

                    b.Property<string>("BookingReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("booking_reference");

                    b.Property<DateOnly?>("CheckIn")
                        .HasColumnType("date")
                        .HasColumnName("check_in");

                    b.Property<DateOnly?>("CheckOut")
                        .HasColumnType("date")
                        .HasColumnName("check_out");

                    b.Property<byte?>("Children")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("children");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("total_price");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("BookingId")
                        .HasName("PK__tblBooki__5DE3A5B18C8ACDC1");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "BookingReference" }, "UQ__tblBooki__BADA455927423170")
                        .IsUnique()
                        .HasFilter("[booking_reference] IS NOT NULL");

                    b.ToTable("tblBookings", (string)null);
                });

            modelBuilder.Entity("Travely.Models.TblHotel", b =>
                {
                    b.Property<int>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("hotel_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HotelId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("address");

                    b.Property<string>("CancellationPolicy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cancellation_policy");

                    b.Property<TimeOnly?>("CheckInTime")
                        .HasColumnType("time")
                        .HasColumnName("check_in_time");

                    b.Property<TimeOnly?>("CheckOutTime")
                        .HasColumnType("time")
                        .HasColumnName("check_out_time");

                    b.Property<decimal?>("Commission")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("commission");

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("contact_info");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fees")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("fees");

                    b.Property<string>("Location")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("name");

                    b.Property<string>("Overview")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("phone");

                    b.Property<byte?>("Stars")
                        .HasColumnType("tinyint")
                        .HasColumnName("stars");

                    b.HasKey("HotelId")
                        .HasName("PK__tblHotel__45FE7E2639928AE5");

                    b.HasIndex(new[] { "Name" }, "UQ__tblHotel__72E12F1BED7C40EC")
                        .IsUnique()
                        .HasFilter("[name] IS NOT NULL");

                    b.ToTable("tblHotels", (string)null);
                });

            modelBuilder.Entity("Travely.Models.TblHotelImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("image_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<int>("HotelId")
                        .HasColumnType("int")
                        .HasColumnName("hotel_id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("image_url");

                    b.HasKey("ImageId")
                        .HasName("PK__tblHotel__DC9AC95586FE2E59");

                    b.HasIndex("HotelId");

                    b.ToTable("tblHotelImages", (string)null);
                });

            modelBuilder.Entity("Travely.Models.TblPayment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("amount");

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("payment_date")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("pending")
                        .HasColumnName("payment_status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("PaymentId")
                        .HasName("PK__tblPayme__ED1FC9EA50A456C9");

                    b.HasIndex("BookingId");

                    b.HasIndex("UserId");

                    b.ToTable("tblPayments", (string)null);
                });

            modelBuilder.Entity("Travely.Models.TblReview", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("review_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("comment");

                    b.Property<int>("HelpfulCount")
                        .HasColumnType("int")
                        .HasColumnName("helpful_count");

                    b.Property<byte?>("Rating")
                        .HasColumnType("tinyint")
                        .HasColumnName("rating");

                    b.Property<DateTime>("ReviewDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("review_date")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("ReviewId")
                        .HasName("PK__tblRevie__60883D90A84AA0C2");

                    b.HasIndex(new[] { "BookingId" }, "UQ__tblRevie__5DE3A5B0889ABF13")
                        .IsUnique();

                    b.ToTable("tblReviews", (string)null);
                });

            modelBuilder.Entity("Travely.Models.TblRoom", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<byte?>("BedsCount")
                        .HasColumnType("tinyint")
                        .HasColumnName("beds_count");

                    b.Property<bool>("BreakfastIncluded")
                        .HasColumnType("bit")
                        .HasColumnName("breakfast_included");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("HotelId")
                        .HasColumnType("int")
                        .HasColumnName("hotel_id");

                    b.Property<byte?>("MaxGuests")
                        .HasColumnType("tinyint")
                        .HasColumnName("max_guests");

                    b.Property<bool>("PetsAllowed")
                        .HasColumnType("bit")
                        .HasColumnName("pets_allowed");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price");

                    b.Property<string>("RoomNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("room_number");

                    b.Property<string>("RoomType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("room_type");

                    b.HasKey("RoomId")
                        .HasName("PK__tblRooms__19675A8A9EDAE80E");

                    b.HasIndex("HotelId");

                    b.ToTable("tblRooms", (string)null);
                });

            modelBuilder.Entity("Travely.Models.TblRoomImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("image_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("image_url");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("room_id");

                    b.HasKey("ImageId")
                        .HasName("PK__tblRoomI__DC9AC955108AD689");

                    b.HasIndex("RoomId");

                    b.ToTable("tblRoomImages", (string)null);
                });

            modelBuilder.Entity("Travely.Models.TblUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<byte?>("Age")
                        .HasColumnType("tinyint")
                        .HasColumnName("age");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("fullname");

                    b.Property<int?>("HotelId")
                        .HasColumnType("int")
                        .HasColumnName("hotel_id");

                    b.Property<string>("Imagepath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("imagepath");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("customer")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.HasKey("UserId")
                        .HasName("PK__tblUsers__B9BE370F4D5024FC");

                    b.HasIndex("HotelId");

                    b.HasIndex(new[] { "Email" }, "UQ__tblUsers__AB6E616422F1317D")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.ToTable("tblUsers", (string)null);
                });

            modelBuilder.Entity("Travely.Models.TblUserHotelBooking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("BookingDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("booking_date")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("HotelId")
                        .HasColumnType("int")
                        .HasColumnName("hotel_id");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("BookingId")
                        .HasName("PK__tblUserH__5DE3A5B18D70EFC5");

                    b.HasIndex("HotelId");

                    b.HasIndex("UserId");

                    b.ToTable("tblUserHotelBooking", (string)null);
                });

            modelBuilder.Entity("Travely.Models.TblWishList", b =>
                {
                    b.Property<int>("WishlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("wishlist_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WishlistId"));

                    b.Property<DateTime>("AddedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("added_date")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("HotelId")
                        .HasColumnType("int")
                        .HasColumnName("hotel_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("WishlistId")
                        .HasName("PK__tblWishL__6151514E8CC42492");

                    b.HasIndex("HotelId");

                    b.HasIndex("UserId");

                    b.ToTable("tblWishList", (string)null);
                });

            modelBuilder.Entity("LkpAmenityTblHotel", b =>
                {
                    b.HasOne("Travely.Models.LkpAmenity", null)
                        .WithMany()
                        .HasForeignKey("AmenitiesAmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Travely.Models.TblHotel", null)
                        .WithMany()
                        .HasForeignKey("HotelsHotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Travely.Models.TblBooking", b =>
                {
                    b.HasOne("Travely.Models.TblRoom", "Room")
                        .WithMany("TblBookings")
                        .HasForeignKey("RoomId")
                        .IsRequired()
                        .HasConstraintName("FK_Booking_Room");

                    b.HasOne("Travely.Models.TblUser", "User")
                        .WithMany("TblBookings")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Booking_User");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Travely.Models.TblHotelImage", b =>
                {
                    b.HasOne("Travely.Models.TblHotel", "Hotel")
                        .WithMany("TblHotelImages")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HotelImage_Hotel");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Travely.Models.TblPayment", b =>
                {
                    b.HasOne("Travely.Models.TblBooking", "Booking")
                        .WithMany("TblPayments")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK_Payment_Booking");

                    b.HasOne("Travely.Models.TblUser", "User")
                        .WithMany("TblPayments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Payment_User");

                    b.Navigation("Booking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Travely.Models.TblReview", b =>
                {
                    b.HasOne("Travely.Models.TblUserHotelBooking", "Booking")
                        .WithOne("TblReview")
                        .HasForeignKey("Travely.Models.TblReview", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Review_Booking");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Travely.Models.TblRoom", b =>
                {
                    b.HasOne("Travely.Models.TblHotel", "Hotel")
                        .WithMany("TblRooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Room_Hotel");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Travely.Models.TblRoomImage", b =>
                {
                    b.HasOne("Travely.Models.TblRoom", "Room")
                        .WithMany("TblRoomImages")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RoomImage_Room");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Travely.Models.TblUser", b =>
                {
                    b.HasOne("Travely.Models.TblHotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Travely.Models.TblUserHotelBooking", b =>
                {
                    b.HasOne("Travely.Models.TblHotel", "Hotel")
                        .WithMany("TblUserHotelBookings")
                        .HasForeignKey("HotelId")
                        .IsRequired()
                        .HasConstraintName("FK_UHB_Hotel");

                    b.HasOne("Travely.Models.TblUser", "User")
                        .WithMany("TblUserHotelBookings")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UHB_User");

                    b.Navigation("Hotel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Travely.Models.TblWishList", b =>
                {
                    b.HasOne("Travely.Models.TblHotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_WishList_Hotel");

                    b.HasOne("Travely.Models.TblUser", "User")
                        .WithMany("TblWishLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_WishList_User");

                    b.Navigation("Hotel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Travely.Models.TblBooking", b =>
                {
                    b.Navigation("TblPayments");
                });

            modelBuilder.Entity("Travely.Models.TblHotel", b =>
                {
                    b.Navigation("TblHotelImages");

                    b.Navigation("TblRooms");

                    b.Navigation("TblUserHotelBookings");
                });

            modelBuilder.Entity("Travely.Models.TblRoom", b =>
                {
                    b.Navigation("TblBookings");

                    b.Navigation("TblRoomImages");
                });

            modelBuilder.Entity("Travely.Models.TblUser", b =>
                {
                    b.Navigation("TblBookings");

                    b.Navigation("TblPayments");

                    b.Navigation("TblUserHotelBookings");

                    b.Navigation("TblWishLists");
                });

            modelBuilder.Entity("Travely.Models.TblUserHotelBooking", b =>
                {
                    b.Navigation("TblReview");
                });
#pragma warning restore 612, 618
        }
    }
}
