// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travely.Models;

public partial class LkpAmenity
{
    public int AmenityId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<TblHotel> Hotels { get; set; } = new List<TblHotel>();
}