// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travely.Models;

public partial class TblBooking
{
    public int BookingId { get; set; }

    public int UserId { get; set; }

    public int RoomId { get; set; }

    public DateOnly? CheckIn { get; set; }

    public DateOnly? CheckOut { get; set; }

    public string Status { get; set; }

    public decimal TotalPrice { get; set; }

    public string BookingReference { get; set; }

    public int Adults { get; set; }

    public int? Children { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual TblRoom Room { get; set; }

    public virtual ICollection<TblPayment> TblPayments { get; set; } = new List<TblPayment>();

    public virtual TblUser User { get; set; }
}