// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travely.Models;

public partial class TblReview
{
    public int ReviewId { get; set; }

    public int BookingId { get; set; }

    public byte? Rating { get; set; }

    public string Comment { get; set; }

    public DateTime ReviewDate { get; set; }

    public int HelpfulCount { get; set; }

    public virtual TblUserHotelBooking Booking { get; set; }
}