// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Travely.Models;

public partial class TblUser
{
    public int UserId { get; set; }

    public string Fullname { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public string Phone { get; set; }

    public byte? Age { get; set; }

    public string Role { get; set; }

    public string Imagepath { get; set; }

    public string Country { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }
    public int? HotelId { get; set; }
    [ForeignKey("HotelId")]
    public TblHotel? Hotel { get; set; }


    public virtual ICollection<TblBooking> TblBookings { get; set; } = new List<TblBooking>();

    public virtual ICollection<TblPayment> TblPayments { get; set; } = new List<TblPayment>();

    public virtual ICollection<TblUserHotelBooking> TblUserHotelBookings { get; set; } = new List<TblUserHotelBooking>();

    public virtual ICollection<TblWishList> TblWishLists { get; set; } = new List<TblWishList>();
}