// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travely.Models;

public partial class TblUserHotelBooking
{
    public int BookingId { get; set; }

    public int UserId { get; set; }

    public int HotelId { get; set; }

    public DateTime BookingDate { get; set; }

    public string Status { get; set; }

    public virtual TblHotel Hotel { get; set; }

    public virtual TblReview TblReview { get; set; }

    public virtual TblUser User { get; set; }
}