// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Travely.Models;

public partial class TblWishList
{
    public int WishlistId { get; set; }

    public int UserId { get; set; }

    public int HotelId { get; set; }

    public DateTime AddedDate { get; set; }

    public virtual TblUser User { get; set; }
    public virtual TblHotel Hotel { get; set; }

}